### ISSUE TITLE
Button "show player" does not appear in Cinnamon

### ISSUE THREAD

**Issue by Goodevil95** [Serranya/deadbeef-mpris2-plugin#30]
Here are two screenshots, first with DeadBeef without the button and with Lollypop, which has this button. I tried release and git version of DeadBeef, tried to switch GTK2/GTK3 interface and "show tray icon" option in settings, but nothing helps.
<a target="_blank" href="https://itmages.ru/image/view/6191350/35807a71"><img src="http://storage3.static.itmages.ru/i/17/1021/s_1508622448_5419136_35807a7195.png" /></a><a target="_blank" href="https://itmages.ru/image/view/6191351/bf45ba17"><img src="http://storage3.static.itmages.ru/i/17/1021/s_1508622448_5331738_bf45ba171a.png" /></a>

**Comment by Serranya** [comment]
Ahh yes. That is because some optional functionality is still missing in the plugin. In this case the ability to put the player in the foreground.

I have not yet figured out how to do it.

**Comment by saivert** [comment]
I was implementing this actually but hit a problem with the window manager (mutter) preventing focus stealing. I was using [gtk_window_present](https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-present). Some MPRIS clients handle this themselves and does not require the Raise() method to be implemented.

**Comment by Goodevil95** [comment]
@saivert It would be cool, If you implement this. I tested this plugin in KDE and have the same bug: I can't show player when I hide player in tray.

**Comment by saivert** [comment]
A better solution is if the client implements activating the application based on the DesktopEntry in the MPRIS2 specification. This is what the GNOME Shell built-in client does.

Activating a running application relies on window manager interaction otherwise most window managers will prevent focus stealing and only flash the taskbar/dock icon for the application.

I have some code which simply launches deadbeef which may work in some instances. The problem with this is that I have to selectively return true for CanRaise depending on which client is calling us because if I return true for CanRaise then the client will use the Raise method instead of its own better method for activating an application.

**Comment by Goodevil95** [comment]
@saivert Thank you, now works :)
