### ISSUE TITLE
bring into foreground is broken in portable deadbeef

### ISSUE THREAD

**Issue by Meru** [Serranya/deadbeef-mpris2-plugin#42]
Currently, to bring deadbeef to foreground, plugin looks for deadbeef.desktop and launches it. This is not possible to do in case we are using portable deadbeef, which is currently THE official way of distribution. In this case deadbeef.desktop does not exist and even if we'll make one, this effectively makes the program no longer portable.

Deadbeef developer suggested that the following should be used instead:
`deadbeef->sendmessage (DB_EV_ACTIVATED, 0, 0, 0);`

**Comment by saivert** [comment]
This is not guaranteed to work either way due to GNOME SHELL being strict about focus stealing and doing everything possible (including heuristics) to thwart any such attempts to bring a window to foreground that is not a response to user action. Since D-BUS calls are completely decoupled from GUI actions and async in nature this hack by launching the .desktop file is the only thing that I found working so far.

I'm open to suggestions.

**Comment by Meru** [comment]
If looking for deadbeef.desktop behaves in the right way, it should also be possible to look for a binary of a process and start that binary instead? Wouldn't that work the same way and remain portable?

**Comment by saivert** [comment]
@Meru try the most recent code 76b5bf72fefad2052e24eb49190a36275da1536c
It will simply call deadbeef->sendmessage (DB_EV_ACTIVATED, 0, 0, 0) if it cannot find a desktop file.

**Comment by Meru** [comment]
@saivert I might need to test better, but so far seem to be working for me on mint 19.1 (ubuntu 18.04)
