### ISSUE TITLE
Album art no longer works with Deadbeef 1.9.1

### ISSUE THREAD

**Issue by gnarlsnishi** [Serranya/deadbeef-mpris2-plugin#51]
I have the following GNOME extension installed (https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button), which used to show an album art thumbnail and no longer does, now just showing the Deadbeef logo instead. All other MPRIS functionality works perfectly.

I installed Deadbeef 1.9.1 from the official deb package, and am using Ubuntu 22.04.

Thank you!

**Comment by kuba160** [comment]
It seems like author of this plugin is not working on it anymore. DeaDBeeF since 1.9 uses newer artwork plugin that is not code-compatible with the older one. I updated the mpris plugin to use newer artwork some time ago which can be found here: https://github.com/kuba160/deadbeef-mpris2-plugin/tree/artwork

There is another version by @sig7x that also works with newer artwork: https://github.com/sig7x/deadbeef-mpris2-plugin/tree/db-1.9

Since this repository probably won't be updated anymore, I asked the author of deadbeef to host the plugin under [DeaDBeeF-Player](https://github.com/DeaDBeeF-Player) organisation so that there will be only one place where everybody could contribute. I will send an update here when I know more details.

**Comment by gnarlsnishi** [comment]
Thank you! Your version works perfectly for me.

**Comment by kuba160** [comment]
The new repository is up: https://github.com/DeaDBeeF-Player/deadbeef-mpris2-plugin

I already sent a PR that includes newer artwork implementation based on version I made previously. After it is merged I assume it will replace previous version from plugin-builder and will be available to download [here](https://deadbeef.sourceforge.io/plugins.html).

I suggest you to keep this issue open so that everyone can easily find this thread and locate version that is more up-to-date.

**Comment by gnarlsnishi** [comment]
Reopened. Thanks.

**Comment by Serranya** [comment]
Im closing this as this plugin is no longer maintained here. Please use https://github.com/DeaDBeeF-Player/deadbeef-mpris2-plugin instead.
